---
- hosts: webservers
  tasks:
    - name: Install php (Debian)
      package:
        name: php
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Install php (RedHat)
      package:
        name: 
          - php
          - php-fpm
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: Create phpinfo.php
      copy:
        dest: /var/www/html/phpinfo.php
        mode: 0644
        content: |
          <?php
          phpinfo();
          ?>
    
    - name: Restart web server
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: restarted
